dataset:
  train:
    name: "mnist"
    version: "v1"  # original MNIST
    params:
      batch_size: 32
  
  eval:
    - name: "mnist_test"
      version: "v1"
      description: "Standard MNIST test set"
    - name: "mnist_balanced"
      version: "v1"
      description: "Class-balanced MNIST test set"
    - name: "mnist_noisy"
      version: "v1" 
      description: "MNIST test set with added noise"
    - name: "mnist_adversarial"
      version: "v1"
      description: "MNIST test set with FGSM adversarial attacks"
      params:
        epsilon: 0.3  # Perturbation magnitude

metrics:
  version: "v1"  # original metrics
  definitions:
    accuracy: "standard accuracy (correct/total)"
    f1: "weighted average f1 score"

model:
  name: "baseline_cnn"
  params:
    input_shape: [1, 28, 28]
    hidden_dims: [32, 64]
    num_classes: 10
    learning_rate: 0.001

tracking:
  save_predictions: true
  log_confusion_matrix: true
  slice_by:
    - "class_distribution"
    - "prediction_confidence" 