dataset:
  name: "mnist"  # dataset identifier
  type: "classification"  # classification, regression, etc
  params:
    train_path: "data/raw/mnist/train"
    test_path: "data/raw/mnist/test"
    val_split: 0.1
    batch_size: 32

model:
  name: "baseline_cnn"  # model identifier
  type: "pytorch"  # framework: pytorch, tensorflow, custom, etc
  params:
    input_shape: [1, 28, 28]
    hidden_dims: [32, 64]
    num_classes: 10
    learning_rate: 0.001
    dropout_rate: 0.1

metrics:
  primary:
    - name: "accuracy"
      threshold: 0.70  # minimum acceptable value
  secondary:
    - name: "precision"
      average: "weighted"
    - name: "recall"
      average: "weighted"
    - name: "f1"
      average: "weighted"
  
tracking:
  save_predictions: true
  log_confusion_matrix: true
  slice_by:
    - "class_distribution"
    - "prediction_confidence" 